apiVersion: v1
kind: Template
metadata:
  name: mvn-docker-build
parameters:
  - name: ENVIRONMENT
  - name: APPLICATION
  - name: COMPONENT
  - name: TAG_VERSION
  - name: JAR_VERSION
    value: 0.1.0
objects:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APPLICATION}-${COMPONENT}
      namespace: ${APPLICATION}-${ENVIRONMENT}

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APPLICATION}-${COMPONENT}-${TAG_VERSION}
      namespace: ${APPLICATION}-${ENVIRONMENT}
    spec:
      runPolicy: Serial
      source:
        type: Binary
        binary:
          asFile: ${APPLCATION}-${COMPONENT}-${JAR_VERSION}.jar
      strategy:
        type: Docker
        dockerStrategy:
          buildArgs:
            - name: JAR_VERSION
              value: ${JAR_VERSION}
          from:
            kind: DockerImage
            name: fabric8/java-centos-openjdk8-jre:latest
      output:
        to:
          kind: ImageStreamTag
          namespace: ${APPLICATION}-${ENVIRONMENT}
          name: ${APPLICATION}-${COMPONENT}:${TAG_VERSION}



