apiVersion: v1
kind: Template
metadata:
  name: mvn-docker-build
parameters:
  - name: APPLICATION
    value: "hello"
  - name: COMPONENT
    required: true
  - name: TAG_VERSION
    required: true
objects:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APPLICATION}-${COMPONENT}

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${APPLICATION}-${COMPONENT}-${TAG_VERSION}
    spec:
      runPolicy: Serial
      source:
        type: Binary
        binary:
          asFile: ${APPLCATION}-${COMPONENT}-*.jar
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: fabric8/java-centos-openjdk8-jre:latest
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION}-${COMPONENT}:${TAG_VERSION}



